### ISSUE TITLE
Make the Code public

### ISSUE THREAD

**Issue by Radonirinaunimi** [NNPDF/nnusf#79]
Followings are a few things that should be addressed in the view of making the code public:

```[tasklist]
### Tasks
- [x] Merge https://github.com/NNPDF/nnusf/pull/77
- [x] Finally fix Workflow https://github.com/NNPDF/nnusf/pull/46
- [x] ~Merge https://github.com/NNPDF/nnusf/pull/76~
- [x] Clean the repo by removing folders that do not belong to the package. These are: [pdfs_lo](https://github.com/NNPDF/nnusf/tree/main/pdfs_lo), [validation](https://github.com/NNPDF/nnusf/tree/main/validation), [xsec-grids](https://github.com/NNPDF/nnusf/tree/main/xsec-grids), [yad_bench](https://github.com/NNPDF/nnusf/tree/main/yad_bench). These folders should instead be moved to the paper directory.
- [x] Rename repository and package to NNSFnu in order to be consistent with the paper ⚠️ 
- [x] Update **documentation**. This includes: add a couple of representative plot(s), create a page that links to the LHAPDF grids and NNSFnu model.
- [x] Deploy package to PyPI (write the corresponding github action).
- [x] Merge #80
- [x] Merge #82
```
