### ISSUE TITLE
PyPI package is broken

### ISSUE THREAD

**Issue by Radonirinaunimi** [NNPDF/nnusf#84]
The relative imports from `pip install nnusf` is broken which means that the contents of `commondata` and `coefficients` could not be accessed. The proposed solution is the following:

```[tasklist]
### Tasks
- [ ] Remove the `commondata` and `coefficients` from the Wheel.
- [ ] Store these data in some server where they are publicly available.
- [ ] Add a script in [nnusf/scripts](https://github.com/NNPDF/nnusf/tree/main/src/nnusf/scripts) to download the data and use [appdirs](https://github.com/ActiveState/appdirs) to both (a) store them in the platform specific directories and (b) call them in the modules.
```
In this case, the imports will be exactly the same for the development and pip-installation mode. Optionally, one can add versioning to the data and dump the version in the output metadata to make sure that everything is consistent.
